import { ColorModeScript } from '@chakra-ui/react'
import { Html, Head, Main, NextScript } from 'next/document'
import theme from '../services/_theme'

export default function Document () {
  return (
  <Html lang='en'>
   <Head>
   <title>Afiliated Pirate</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="UTF-8" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no"/>
        <link rel="icon" href="/favicon.ico" />
   </Head>
   <body>
     <ColorModeScript initialColorMode={theme.config.initialColorMode} />
     <Main />
     <NextScript />
   </body>
  </Html>
  )
}
