import { Box, Button, Heading, Text, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link';
import {IoIosLock} from 'react-icons/io'
export default function AccessDenied () {
  return (
    <>
      <Head>
        <title>Access Denied</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box bg="#000" height={'100vh'} width="100vw" pos={'fixed'} top={'0'} left={'0'} zIndex={'100'} display={'flex'} justifyContent={'center'} alignItems={'center'}>
      <VStack spacing={4}>
        <Box>
        <IoIosLock fontSize={'130px'} color='#01FBFB' />

        </Box>
    
        <Heading color='white' fontSize={'45px'}>
        Access denied
        </Heading>
<Text fontWeight={'normal'}>You don't have permissions to access this page.</Text>
      <Box>
      <Link href="/">
      <Button
            border='1px solid #01FBFB'
            fontSize={'12px'}
            mt={8} backgroundColor={"#000"} color={" #01FBFB"} minW={'200px'}>
        Back to home
            </Button></Link>
      </Box>
      </VStack>



      </Box>

    </>

  )
}